import { analyzeInBrowser, browserEngineHealth } from './browser-engine/pipeline.js';

const MAX_IMAGES=4,INSTRUMENTS=['AUTO','NQ','MNQ','ES'],TIMEFRAMES=['AUTO','1m','3m','5m','15m','30m','1H','4H','1D'];
const state={shots:[],analyzing:false,extensionReady:false,bridgeState:null,liveEnabled:localStorage.getItem('ictbrain-live-enabled')!=='false',intervalSec:Number(localStorage.getItem('ictbrain-live-interval')||30),timer:null,lastFingerprint:'',lastResult:null,lastScanAt:0,lastConnectedCount:0};
const $=id=>document.getElementById(id),els={status:$('backendStatus'),bridge:$('bridgeStatus'),connected:$('connectedCount'),liveToggle:$('liveToggle'),interval:$('interval'),scan:$('scanLive'),liveResult:$('liveResult'),liveError:$('liveError'),lastScan:$('lastScan'),lifecycle:$('lifecycleState'),files:$('files'),shots:$('shots'),count:$('count'),analyze:$('analyze'),progress:$('progress'),progressText:$('progressText'),result:$('result')};
const pending=new Map();
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(v){return Number.isFinite(Number(v))?Number(v).toFixed(2).replace(/\.00$/,''):'—';}
function fmtTime(ms){if(!Number(ms))return'Never';try{return new Date(Number(ms)).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});}catch{return'—';}}
function list(items){const a=Array.isArray(items)?items.filter(Boolean):[];return a.length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="hint">None listed.</p>';}
function tradeMarkup(payload){const r=payload?.result;if(!r)return'<h2 class="decision wait">Wait.</h2><p class="setup">No scan result yet.</p>';const cls=r.decision==='LONG'?'long':r.decision==='SHORT'?'short':'wait',actionable=['LONG','SHORT'].includes(r.decision),numbers=actionable?`<div class="numbers"><div class="number"><small>ENTRY</small><b>${money(r.entry)}</b></div><div class="number"><small>STOP</small><b>${money(r.stop)}</b></div><div class="number"><small>TAKE PROFIT</small><b>${money(r.target)}</b></div><div class="number"><small>R:R</small><b>${Number(r.rr).toFixed(2)}</b></div></div>`:'';return`<div class="result-head"><div><h2 class="decision ${cls}">${r.decision==='WAIT'?'Wait.':r.decision==='LONG'?'Long.':'Short.'}</h2><p class="setup">${esc(r.setupId||'NONE')} · ${esc(r.setup||'No validated trade')}</p></div><span class="confidence">${Math.round(r.confidence||0)}% evidence</span></div><p class="hint"><b>Lifecycle:</b> ${esc(r.lifecycle?.stage||'WATCHING')} · ${esc(r.lifecycle?.reason||'')}</p>${numbers}<div class="grid"><div class="tile"><small>Instrument</small><b>${esc(r.instrument||'—')}</b></div><div class="tile"><small>Bias</small><b>${esc(r.bias||'NEUTRAL')}</b></div><div class="tile"><small>Draw on liquidity</small><b>${esc(r.dol||'—')}</b></div><div class="tile"><small>Execution chart</small><b>${esc(r.executionLabel||'—')}</b></div></div>${r.reason?`<p class="error"><b>Why WAIT:</b> ${esc(r.reason)}</p>`:''}${r.trigger?`<h3>Entry trigger</h3><p>${esc(r.trigger)}</p>`:''}${r.invalidation?`<h3>Invalidation</h3><p>${esc(r.invalidation)}</p>`:''}<h3>Evidence</h3>${list(r.evidence)}<h3>Uncertainty</h3>${list(r.uncertainty)}<p class="hint">Browser-native ICT Brain ${esc(payload.meta?.backendVersion||'6.4')} · ${(Number(payload.meta?.processingMs||0)/1000).toFixed(1)}s · no server backend · no external model API.</p>`;}
function setStatus(){const h=browserEngineHealth();els.status.textContent=`Browser engine ${h.version} ready`;els.status.className='pill ok';}
function requestExtension(payload,timeout=12000){return new Promise((resolve,reject)=>{const id=`ib-${Date.now()}-${Math.random().toString(36).slice(2)}`,timer=setTimeout(()=>{pending.delete(id);reject(new Error('ICT Brain Live Bridge did not respond. Reload the ICT Brain page after updating the extension.'));},timeout);pending.set(id,{resolve,reject,timer});window.postMessage({source:'ict-brain-web',type:'ICT_EXTENSION_REQUEST',id,payload},'*');});}
window.addEventListener('message',event=>{if(event.source!==window)return;const m=event.data;if(m?.source!=='ict-brain-extension')return;if(m.type==='ICT_EXTENSION_READY'){state.extensionReady=true;refreshBridge();return;}if(m.type==='ICT_EXTENSION_RESPONSE'&&m.id&&pending.has(m.id)){const p=pending.get(m.id);clearTimeout(p.timer);pending.delete(m.id);p.resolve(m.response);}});
async function refreshBridge(){try{const r=await requestExtension({type:'ICT_GET_STATE'});if(!r?.ok)throw new Error(r?.error||'Bridge state unavailable.');state.extensionReady=true;state.bridgeState=r.state;renderBridge();}catch{state.extensionReady=false;state.bridgeState=null;renderBridge();}}
function clearLiveTimer(){if(state.timer){clearTimeout(state.timer);state.timer=null;}}
function connectedCount(){return Object.keys(state.bridgeState?.connectedTabs||{}).length;}
function scheduleLive(immediate=false){const count=connectedCount();if(!state.liveEnabled||!state.extensionReady||count===0){clearLiveTimer();return;}if(state.timer)return;const delay=immediate?900:Math.max(15,state.intervalSec)*1000;state.timer=setTimeout(async()=>{state.timer=null;await runLiveScan(false);scheduleLive(false);},delay);}
function renderBridge(){const s=state.bridgeState,count=Object.keys(s?.connectedTabs||{}).length,stackChanged=count!==state.lastConnectedCount;state.lastConnectedCount=count;els.connected.textContent=`${count} / 5`;els.bridge.textContent=state.extensionReady?(count?`Live Bridge connected · ${count} chart${count===1?'':'s'}`:'Live Bridge ready · connect TradingView charts from the extension'):'Live Bridge extension not detected';els.liveToggle.checked=state.liveEnabled;els.interval.value=String(state.intervalSec);els.scan.disabled=!state.extensionReady||state.analyzing||count===0;els.lastScan.textContent=fmtTime(state.lastScanAt);els.lifecycle.textContent=state.lastResult?.result?.lifecycle?.stage||'WATCHING';if(state.lastResult)els.liveResult.innerHTML=tradeMarkup(state.lastResult);if(stackChanged&&count>0&&state.liveEnabled){clearLiveTimer();scheduleLive(true);}else scheduleLive(false);}
function fingerprint(capture){return(capture?.screenshots||[]).map(x=>`${x.instrument||'AUTO'}:${x.timeframe||'AUTO'}:${x.captureFingerprint||''}`).join('|');}
async function runLiveScan(manual=false){if(state.analyzing||!state.extensionReady||connectedCount()===0)return;state.analyzing=true;els.scan.disabled=true;els.liveError.textContent='';try{els.bridge.textContent='Capturing connected TradingView charts…';const r=await requestExtension({type:'ICT_CAPTURE_STACK'},30000);if(!r?.ok)throw new Error(r?.error||'Could not capture TradingView charts.');const sig=fingerprint(r.capture);if(!manual&&sig&&sig===state.lastFingerprint){state.lastScanAt=Date.now();els.lastScan.textContent=fmtTime(state.lastScanAt);els.bridge.textContent='No chart change · analysis skipped';return;}state.lastFingerprint=sig;els.bridge.textContent='Analyzing inside this webpage…';const payload=await analyzeInBrowser(r.capture.screenshots);if(!payload?.ok)throw new Error(payload?.error||'Browser-native analysis failed.');state.lastResult=payload;state.lastScanAt=Date.now();els.liveResult.innerHTML=tradeMarkup(payload);els.lastScan.textContent=fmtTime(state.lastScanAt);els.lifecycle.textContent=payload.result?.lifecycle?.stage||'WATCHING';els.bridge.textContent='Live analysis complete';}catch(e){els.liveError.textContent=e?.message||'Live scan failed.';}finally{state.analyzing=false;els.scan.disabled=!state.extensionReady||connectedCount()===0;await refreshBridge();}}
els.scan.onclick=()=>runLiveScan(true);els.liveToggle.onchange=()=>{state.liveEnabled=els.liveToggle.checked;localStorage.setItem('ictbrain-live-enabled',String(state.liveEnabled));clearLiveTimer();scheduleLive(state.liveEnabled&&state.lastScanAt===0);};els.interval.onchange=()=>{state.intervalSec=Math.max(15,Number(els.interval.value)||30);localStorage.setItem('ictbrain-live-interval',String(state.intervalSec));clearLiveTimer();scheduleLive(false);};

els.files.addEventListener('change',event=>{const incoming=[...(event.target.files||[])].filter(f=>/^image\/(png|jpeg|webp)$/.test(f.type)),remain=Math.max(0,MAX_IMAGES-state.shots.length);for(const file of incoming.slice(0,remain))state.shots.push({file,url:URL.createObjectURL(file),instrument:'AUTO',timeframe:'AUTO'});event.target.value='';renderShots();});
function renderShots(){els.count.textContent=`${state.shots.length} / ${MAX_IMAGES}`;els.shots.innerHTML='';state.shots.forEach((shot,i)=>{const card=document.createElement('article');card.className='shot';card.innerHTML=`<img src="${shot.url}" alt="Screenshot ${i+1}"><div class="shot-body"><div class="shot-top"><span>Screenshot ${i+1}</span><button class="remove" type="button">×</button></div><div class="meta"><select>${INSTRUMENTS.map(v=>`<option${v===shot.instrument?' selected':''}>${v}</option>`).join('')}</select><select>${TIMEFRAMES.map(v=>`<option${v===shot.timeframe?' selected':''}>${v}</option>`).join('')}</select></div></div>`;const selects=card.querySelectorAll('select');selects[0].onchange=e=>shot.instrument=e.target.value;selects[1].onchange=e=>shot.timeframe=e.target.value;card.querySelector('.remove').onclick=()=>{URL.revokeObjectURL(shot.url);state.shots.splice(i,1);renderShots();};els.shots.appendChild(card);});els.analyze.disabled=!state.shots.length||state.analyzing;}
async function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
els.analyze.onclick=async()=>{if(state.analyzing||!state.shots.length)return;state.analyzing=true;els.progress.hidden=false;els.progressText.textContent='Analyzing locally in your browser…';els.analyze.disabled=true;els.result.hidden=true;try{const shots=[];for(const s of state.shots)shots.push({dataUrl:await fileToDataUrl(s.file),instrument:s.instrument,timeframe:s.timeframe,timeHints:[],priceHints:[],timezoneHint:''});const payload=await analyzeInBrowser(shots);els.result.innerHTML=tradeMarkup(payload);els.result.hidden=false;}catch(e){els.result.innerHTML=`<h2 class="decision wait">Couldn’t analyze.</h2><p class="error">${esc(e?.message||'Browser-native analysis failed.')}</p>`;els.result.hidden=false;}finally{state.analyzing=false;els.progress.hidden=true;els.analyze.disabled=!state.shots.length;}};

window.addEventListener('beforeunload',()=>{clearLiveTimer();state.shots.forEach(s=>URL.revokeObjectURL(s.url));});
setStatus();renderShots();renderBridge();setTimeout(refreshBridge,400);setInterval(refreshBridge,10000);
