const $=id=>document.getElementById(id);
let currentTab=null,state=null,detected=null;
const send=message=>chrome.runtime.sendMessage(message);
const validInstrument=v=>['NQ','MNQ','ES'].includes(v);
const validTimeframe=v=>['1m','3m','5m','15m','30m','1H','4H','1D'].includes(v);
function shortTitle(title){const t=String(title||'TradingView').replace(/\s+[—-]\s+TradingView.*$/i,'');return t.length>52?`${t.slice(0,49)}…`:t;}
function isTvTab(tab){return Boolean(tab&&/^https:\/\/([^.]+\.)?tradingview\.com\//i.test(tab.url||''));}
function renderConnected(){const list=$('connectedList'),entries=Object.entries(state?.connectedTabs||{});$('connectedCount').textContent=`${entries.length} / 5`;list.innerHTML='';if(!entries.length){const e=document.createElement('div');e.className='empty';e.textContent='No TradingView charts connected yet.';list.appendChild(e);return;}for(const[tabId,cfg]of entries){const row=document.createElement('div');row.className='connected-item';const info=document.createElement('div');info.innerHTML=`<div class="connected-title">${shortTitle(cfg.title)}</div><div class="connected-meta">${cfg.instrument||'AUTO'} · ${cfg.timeframe||'AUTO'}</div>`;const btn=document.createElement('button');btn.className='disconnect';btn.textContent='Disconnect';btn.onclick=async()=>{const r=await send({type:'ICT_DISCONNECT_TAB',tabId:Number(tabId),forget:true});if(r?.ok){state=r.state;render();}};row.append(info,btn);list.appendChild(row);}}
function renderCurrent(){const isTv=isTvTab(currentTab),connected=currentTab&&state?.connectedTabs?.[String(currentTab.id)];$('currentTab').textContent=currentTab?shortTitle(currentTab.title):'No active tab';$('tabState').textContent=connected?'CONNECTED':isTv?'READY':'NOT TRADINGVIEW';$('connectBtn').disabled=!isTv;$('connectBtn').textContent=connected?'Update connected chart':'Connect current TradingView chart';const di=detected?.instrument,dt=detected?.timeframe;if(validInstrument(di))$('instrument').value=di;else if(connected)$('instrument').value=connected.instrument||'AUTO';if(validTimeframe(dt))$('timeframe').value=dt;else if(connected)$('timeframe').value=connected.timeframe||'AUTO';const meta=$('detectedMeta');if(meta){if(!isTv)meta.textContent='Open a TradingView chart to detect symbol and timeframe.';else if(detected)meta.textContent=`Detected now: ${di||'AUTO'} · ${dt||'AUTO'}${detected?.detection?.timeframeSource?` · ${detected.detection.timeframeSource}`:''}`;else meta.textContent='Detecting current chart…';}}
function render(){renderConnected();renderCurrent();$('error').textContent=state?.lastError||'';$('browserState').textContent=state?.enabled?'READY':'PAUSED';}
async function detectCurrent(){detected=null;if(!isTvTab(currentTab)){renderCurrent();return;}try{const r=await send({type:'ICT_DETECT_TAB',tabId:currentTab.id});if(r?.ok)detected=r.detection||null;else throw new Error(r?.error||'Detection failed.');}catch(e){$('error').textContent=e?.message||'Could not detect the current TradingView chart.';}renderCurrent();}
async function load(){currentTab=(await chrome.tabs.query({active:true,currentWindow:true}))[0]||null;const r=await send({type:'ICT_GET_STATE'});if(!r?.ok)throw new Error(r?.error||'Could not read bridge state.');state=r.state;render();await detectCurrent();}
$('connectBtn').onclick=async()=>{if(!currentTab)return;$('error').textContent='';const instrument=$('instrument').value==='AUTO'&&validInstrument(detected?.instrument)?detected.instrument:$('instrument').value;const timeframe=$('timeframe').value==='AUTO'&&validTimeframe(detected?.timeframe)?detected.timeframe:$('timeframe').value;const r=await send({type:'ICT_CONNECT_TAB',tabId:currentTab.id,instrument,timeframe});if(r?.ok){state=r.state;await detectCurrent();render();}else $('error').textContent=r?.error||'Could not connect chart.';};
load().catch(e=>$('error').textContent=e?.message||'Live Bridge could not initialize.');
